### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by oSadykov**

### CODE REVIEW

**Comment by oSadykov** [comment]
Added readme description.

**Comment by populov** [comment]
good, but I would suggest:
1. Create 'docs' folder in repository root, and there should be files like "ORM.md", "MVC.md" etc.
2. **README.md** should contain Table of Contents with [links](README.md) to corresponding documentation sections.
3. Use _Markdown_ formating to **emphasize** special directories files, ```pieces of code```, etc.

**Comment by populov** [comment]
Ideally I would like to see something similar to Laravel documentation: https://laravel.com/docs/5.6/eloquent
Description (ex. how ORM works), code samples for typical scenarios ("to add new entity you shoud to this", "to display a list of entities", "to display paginated list of entities", "to create edit form", "to create page view"), etc., not just FAQ.

**Comment by sariluong** [comment]
Hi Oleg Sadykov,
I've read your docs and understood somethings. But I need to know more about features.
I think the tutorial should have a concrete example, for example Cake Store project.
And document should focus on how user can create a new project by this framework.

Below are some details I need.

I. Architecture
This chapter should describe about connecting or relation of folders, namespaces or
modules...
1. Backend - frontend lifecycle
2. Backend - API lifecycle
3. API - frontend lifecycle

II. Backend (**It should explain about API in every articles**)
1. Router
- How to create router
- How many ways to create router
- Parameters, methods
2. Controller
- Basic functions of controller
- How to get, set.. data from database
- How to interact with frontend: send value, set variable
- How to debug at backend and frontend
3. Database
- How to connect to database, tables
- Namespace, classes, where to save model files
- How many ways to CRUD data
- How many types of resultset
- Exception, error codes
- Caching
4. Request
- Static varialbes
- Methods (POST, GET...), param, data...
- Ajax request
5. Response
- How to return an ajax response
- Structure of response
- Status codes
6. Ajax
- Where is the best directory to store ajax files
- How to call
- Request, response7. Session
- Configuration
- Create, using, clear, store sessions
8. Cache
- Configuration
- Create, using, clear, store cache
9. Template
- Are there any helper class to work with frontend template
10. Security
- How to survive the SQL Injection
- Frontend validation
- Security token
- Backend authority
11. Error
- How many error type, constants
- Base class of exceptions
- How to send exception at backend, to frontend, to ajax
- Where to save errors: files, database
- Configuration: show error, write to files or db
12. Log
- How many log type, constants
- How to create a custom log
- Base class of log
- Where to log: files, database
- Configuration

 #### API

**Review by populov — APPROVED** [review]

**Pull request merged**
